=== daneeldeveloper/fj-doc/fj-doc-lib-autodoc/src/main/resources/xsd/autodoc-meta-1-0.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xsd:schema xmlns='http://www.w3.org/2000/10/XMLSchema'
	targetNamespace='https://autodocmeta.fugerit.org'
	xmlns:admeta='https://autodocmeta.fugerit.org' xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	
	<xsd:element name='autodocMeta'>
		<xsd:annotation>
			<xsd:documentation>Root of the autodoc details</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref='admeta:admProperty' minOccurs="0" maxOccurs="unbounded" />
				<xsd:element ref='admeta:admChangelog' minOccurs="0" maxOccurs="unbounded" />
				<xsd:element ref='admeta:admSection' minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name='admProperty'>
		<xsd:annotation>
			<xsd:documentation>General properties</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref='admeta:name' minOccurs="1" maxOccurs="1" />
				<xsd:element ref='admeta:description' minOccurs="1" maxOccurs="1" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name='admChangelog'>
		<xsd:annotation>
			<xsd:documentation>General informations</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref='admeta:date' minOccurs="1" maxOccurs="1" />
				<xsd:element ref='admeta:version' minOccurs="1" maxOccurs="1" />
				<xsd:element ref='admeta:description' minOccurs="1" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name='admSection'>
		<xsd:annotation>
			<xsd:documentation>General informations</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref='admeta:name' minOccurs="1" maxOccurs="1" />
				<xsd:element ref='admeta:description' minOccurs="1" maxOccurs="1" />
				<xsd:element ref='admeta:admMetaInfo' minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name='admMetaInfo'>
		<xsd:annotation>
			<xsd:documentation>Details of an meta information</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref='admeta:name' minOccurs="1" maxOccurs="1" />
				<xsd:element ref='admeta:description' minOccurs="1" maxOccurs="1" />
				<xsd:element ref='admeta:defaultValue' minOccurs="0" maxOccurs="1" />
				<xsd:element ref='admeta:since' minOccurs="0" maxOccurs="1" />
				<xsd:element ref='admeta:supportedType' minOccurs="0" maxOccurs="unbounded" />
				<xsd:element ref="admeta:supportedHandler" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name='name'>
		<xsd:annotation>
			<xsd:documentation>Name of an object (Element, Attribute etc.)</xsd:documentation>
		</xsd:annotation>
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:element>
	
	<xsd:element name='description'>
		<xsd:annotation>
			<xsd:documentation>Description of an object (Element, Attribute etc.)</xsd:documentation>
		</xsd:annotation>
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:element>
	
	<xsd:element name='defaultValue'>
		<xsd:annotation>
			<xsd:documentation>The default value for the meta information, if any</xsd:documentation>
		</xsd:annotation>
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:element>
	
	<xsd:element name='status'>
		<xsd:annotation>
			<xsd:documentation>Implementation status of an object (Element, Attribute etc.)</xsd:documentation>
		</xsd:annotation>
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:element>
	
	<xsd:element name='version'>
		<xsd:annotation>
			<xsd:documentation>Description of a version</xsd:documentation>
		</xsd:annotation>
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:element>
	
	<xsd:element name='date'>
		<xsd:annotation>
			<xsd:documentation>Reference date for an information</xsd:documentation>
		</xsd:annotation>
		<xsd:simpleType>
			<xsd:restriction base="xsd:date">
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:element>
	
	<xsd:element name='since'>
		<xsd:annotation>
			<xsd:documentation>Description of a version the feature is supported</xsd:documentation>
		</xsd:annotation>
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:element>	

	<xsd:element name='supportedType'>
		<xsd:annotation>
			<xsd:documentation>A supported type (pdf, xml, html, xlsx etc.)</xsd:documentation>
		</xsd:annotation>
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:element>	
	
	<xsd:element name='supportedHandler'>
		<xsd:annotation>
			<xsd:documentation>A list of known supporting handlers (for instance : fj-doc-freemarker[html] or fj-doc-mod-fop[pdf])</xsd:documentation>
		</xsd:annotation>
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:element>		
		
</xsd:schema>

=== daneeldeveloper/fj-doc/fj-doc-lib-autodoc/src/test/resources/docs/meta_xml/adm_standard_meta_info.xml
<?xml version="1.0" encoding="UTF-8"?>
<admeta:autodocMeta 
	xmlns:admeta="https://autodocmeta.fugerit.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="https://autodocmeta.fugerit.org autodoc-meta-1-0.xsd ">

  <admeta:admProperty>
    <admeta:name>doc-title</admeta:name>
    <admeta:description>Documentation for Venus Doc Format standard meta informations</admeta:description>
  </admeta:admProperty>
  <admeta:admProperty>
    <admeta:name>doc-author</admeta:name>
    <admeta:description>Matteo Franci a.k.a. Fugerit</admeta:description>
  </admeta:admProperty>
  <admeta:admProperty>
    <admeta:name>doc-version</admeta:name>
    <admeta:description>3 (2023-08-17)</admeta:description>
  </admeta:admProperty>
  <admeta:admProperty>
    <admeta:name>doc-subject</admeta:name>
    <admeta:description><![CDATA[This section contains documentation for most &lt;info name="key"&gt;value&lt;/info&gt; of Venus Doc Format]]></admeta:description>
  </admeta:admProperty>
  	  
  <admeta:admProperty>
    <admeta:name>html-css-link</admeta:name>
    <admeta:description>https://venusguides.fugerit.org/src/css/default_venus_docs_style.css</admeta:description>
  </admeta:admProperty>

  <admeta:admChangelog>
    <admeta:date>2023-08-17</admeta:date>
    <admeta:version>3</admeta:version>
    <admeta:description>Added 'default-table-padding', 'default-table-spacing' and 'default-cell-border-width' properties</admeta:description>
  </admeta:admChangelog>

  <admeta:admChangelog>
    <admeta:date>2023-08-15</admeta:date>
    <admeta:version>2</admeta:version>
    <admeta:description>Added fixed size layout and HTML properties</admeta:description>
  </admeta:admChangelog>
  
  <admeta:admChangelog>
    <admeta:date>2023-08-12</admeta:date>
    <admeta:version>1</admeta:version>
    <admeta:description>First version of this document</admeta:description>
  </admeta:admChangelog>
  
  <admeta:admSection>
    <admeta:name>meta_general</admeta:name>
    <admeta:description>Properties for generic metadata</admeta:description>
    <admeta:admMetaInfo>
      <admeta:name>doc-title</admeta:name>
      <admeta:description>Set the document title, should be usually supported in document formats like html or pdf</admeta:description>
      <admeta:since>1.0.0</admeta:since>
      <admeta:supportedType>html</admeta:supportedType>
      <admeta:supportedType>pdf</admeta:supportedType>
      <admeta:supportedHandler>fj-doc-freemarker(html)</admeta:supportedHandler>
      <admeta:supportedHandler>fj-doc-mod-fop(pdf)</admeta:supportedHandler>
    </admeta:admMetaInfo>
    <admeta:admMetaInfo>
      <admeta:name>doc-author</admeta:name>
      <admeta:description>Set the document author, should be usually supported in document formats like html or pdf</admeta:description>
      <admeta:since>1.0.0</admeta:since>
      <admeta:supportedType>html</admeta:supportedType>
      <admeta:supportedType>pdf</admeta:supportedType>
      <admeta:supportedHandler>fj-doc-freemarker(html)</admeta:supportedHandler>
      <admeta:supportedHandler>fj-doc-mod-fop(pdf)</admeta:supportedHandler>
    </admeta:admMetaInfo>
    <admeta:admMetaInfo>
      <admeta:name>doc-creator</admeta:name>
      <admeta:description>Set the document creator tool (es. Venus Doc), should be usually supported in document formats like html or pdf</admeta:description>
      <admeta:since>1.0.0</admeta:since>
      <admeta:supportedType>html</admeta:supportedType>
      <admeta:supportedType>pdf</admeta:supportedType>
      <admeta:supportedHandler>fj-doc-freemarker(html)</admeta:supportedHandler>
      <admeta:supportedHandler>fj-doc-mod-fop(pdf)</admeta:supportedHandler>
    </admeta:admMetaInfo>
    <admeta:admMetaInfo>
      <admeta:name>doc-language</admeta:name>
      <admeta:description>Set the document language, should be usually supported in document formats like html or pdf</admeta:description>
      <admeta:since>1.0.0</admeta:since>
      <admeta:supportedType>html</admeta:supportedType>
      <admeta:supportedType>pdf</admeta:supportedType>
      <admeta:supportedHandler>fj-doc-freemarker(html)</admeta:supportedHandler>
      <admeta:supportedHandler>fj-doc-mod-fop(pdf)</admeta:supportedHandler>
    </admeta:admMetaInfo>
     <admeta:admMetaInfo>
      <admeta:name>doc-subject</admeta:name>
      <admeta:description>Set the document subject, should be usually supported in document formats like html or pdf</admeta:description>
      <admeta:since>1.0.0</admeta:since>
      <admeta:supportedType>html</admeta:supportedType>
      <admeta:supportedType>pdf</admeta:supportedType>
      <admeta:supportedHandler>fj-doc-freemarker(html)</admeta:supportedHandler>
      <admeta:supportedHandler>fj-doc-mod-fop(pdf)</admeta:supportedHandler>
    </admeta:admMetaInfo>
     <admeta:admMetaInfo>
      <admeta:name>doc-version</admeta:name>
      <admeta:description>A custom property to track meta model version</admeta:description>
      <admeta:since>1.0.0</admeta:since>
      <admeta:supportedType>html</admeta:supportedType>
      <admeta:supportedType>pdf</admeta:supportedType>
      <admeta:supportedHandler>fj-doc-freemarker(html)</admeta:supportedHandler>
      <admeta:supportedHandler>fj-doc-mod-fop(pdf)</admeta:supportedHandler>
    </admeta:admMetaInfo>
    <admeta:admMetaInfo>
      <admeta:name>default-table-padding</admeta:name>
      <admeta:description>Set default table padding, default '-1' means 'unset' (shoud be inherited by all cells, in HTML it is handled by 'padding')</admeta:description>
      <admeta:defaultValue>-1</admeta:defaultValue>
      <admeta:since>1.5.0</admeta:since>
      <admeta:supportedType>html</admeta:supportedType>
      <admeta:supportedType>pdf</admeta:supportedType>
      <admeta:supportedType>xls</admeta:supportedType>
      <admeta:supportedType>xlsx</admeta:supportedType>
      <admeta:supportedHandler>fj-doc-freemarker(html)</admeta:supportedHandler>
      <admeta:supportedHandler>fj-doc-poi(xls)</admeta:supportedHandler>
      <admeta:supportedHandler>fj-doc-poi(xlsx)</admeta:supportedHandler>
      <admeta:supportedHandler>fj-doc-mod-fop(pdf)</admeta:supportedHandler>
      <admeta:supportedHandler>fj-doc-mod-openpdf(pdf)</admeta:supportedHandler>
      <admeta:supportedHandler>fj-doc-mod-itext(pdf)</admeta:supportedHandler>
    </admeta:admMetaInfo>
    <admeta:admMetaInfo>
      <admeta:name>default-table-spacing</admeta:name>
      <admeta:description>Set default table spacing, default '-1' means 'unset' (shoud be inherited by all cells, in HTML it is handled by 'margin')</admeta:description>
      <admeta:defaultValue>-1</admeta:defaultValue>
      <admeta:since>1.5.0</admeta:since>
      <admeta:supportedType>html</admeta:supportedType>
      <admeta:supportedType>pdf</admeta:supportedType>
      <admeta:supportedType>xls</admeta:supportedType>
      <admeta:supportedType>xlsx</admeta:supportedType>
      <admeta:supportedHandler>fj-doc-freemarker(html)</admeta:supportedHandler>
      <admeta:supportedHandler>fj-doc-poi(xls)</admeta:supportedHandler>
      <admeta:supportedHandler>fj-doc-poi(xlsx)</admeta:supportedHandler>
      <admeta:supportedHandler>fj-doc-mod-fop(pdf)</admeta:supportedHandler>
      <admeta:supportedHandler>fj-doc-mod-openpdf(pdf)</admeta:supportedHandler>
      <admeta:supportedHandler>fj-doc-mod-itext(pdf)</admeta:supportedHandler>
    </admeta:admMetaInfo>
    <admeta:admMetaInfo>
      <admeta:name>default-cell-border-width</admeta:name>
      <admeta:description>Set default cell border width for all table cells, default '-1' means 'unset'</admeta:description>
      <admeta:defaultValue>-1</admeta:defaultValue>
      <admeta:since>1.5.0</admeta:since>
      <admeta:supportedType>html</admeta:supportedType>
      <admeta:supportedType>pdf</admeta:supportedType>
      <admeta:supportedType>xls</admeta:supportedType>
      <admeta:supportedType>xlsx</admeta:supportedType>
      <admeta:supportedHandler>fj-doc-freemarker(html)</admeta:supportedHandler>
      <admeta:supportedHandler>fj-doc-poi(xls)</admeta:supportedHandler>
      <admeta:supportedHandler>fj-doc-poi(xlsx)</admeta:supportedHandler>
      <admeta:supportedHandler>fj-doc-mod-fop(pdf)</admeta:supportedHandler>
      <admeta:supportedHandler>fj-doc-mod-openpdf(pdf)</admeta:supportedHandler>
      <admeta:supportedHandler>fj-doc-mod-itext(pdf)</admeta:supportedHandler>
    </admeta:admMetaInfo>
  </admeta:admSection>

  <admeta:admSection>
    <admeta:name>meta_html</admeta:name>
    <admeta:description>Properties specific to HTML formata</admeta:description>
    <admeta:admMetaInfo>
      <admeta:name>html-css-link</admeta:name>
      <admeta:description>Link to css for the html document</admeta:description>
      <admeta:since>1.4.5</admeta:since>
      <admeta:supportedType>html</admeta:supportedType>
      <admeta:supportedHandler>fj-doc-freemarker(html)</admeta:supportedHandler>
    </admeta:admMetaInfo>
    <admeta:admMetaInfo>
      <admeta:name>html-css-style</admeta:name>
      <admeta:description>Inline CSS style definition to be added to the document</admeta:description>
      <admeta:since>1.4.5</admeta:since>
      <admeta:supportedType>html</admeta:supportedType>
      <admeta:supportedHandler>fj-doc-freemarker(html)</admeta:supportedHandler>
    </admeta:admMetaInfo>
    <admeta:admMetaInfo>
      <admeta:name>html-add-to-head</admeta:name>
      <admeta:description>Custom HTML code to be added directly in the head section</admeta:description>
      <admeta:since>1.0.0</admeta:since>
      <admeta:supportedType>html</admeta:supportedType>
      <admeta:supportedHandler>fj-doc-freemarker(html)</admeta:supportedHandler>
    </admeta:admMetaInfo>
  </admeta:admSection>

  <admeta:admSection>
    <admeta:name>meta_fixed</admeta:name>
    <admeta:description>Properties specific to fixed size formats (like PDF)</admeta:description>
    <admeta:admMetaInfo>
      <admeta:name>margins</admeta:name>
