=== daneeldeveloper/fj-doc/fj-doc-base/src/main/resources/config/doc-1-0.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!--

	/*
	 * @(#)doc-1-0.xsd
	 *
	 * @project    : org.fugerit.java.doc.base
	 * @creation   : 2019-11-06
	 * @version    : 1.1.0 (2019-11-09)
	 *
	 * XSD for fugerit doc configuration
	 */

	WARNING!!! - DTD remains just for compatibility, but will not be mantained, use XSD       
	
	Sample doc : 	
	
<doc
	xmlns="http://javacoredoc.fugerit.org"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://javacoredoc.fugerit.org http://www.fugerit.org/data/java/doc/xsd/doc-1-0.xsd" > 	
</doc>	
	
-->
<xsd:schema xmlns='http://www.w3.org/2000/10/XMLSchema'
	targetNamespace='http://javacoredoc.fugerit.org'
	xmlns:doc='http://javacoredoc.fugerit.org' xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:element name='doc'>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:choice>
					<xsd:element ref='doc:metadata' />
					<xsd:element ref='doc:meta' />
				</xsd:choice>
				<xsd:element ref='doc:body' />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name='metadata' type="doc:metaType">

	</xsd:element>

	<xsd:element name='meta' type="doc:metaType">

	</xsd:element>

	<xsd:element name='info'>
		<xsd:complexType mixed='true'>
			<xsd:attribute name='name' type='xsd:string' use='required' />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name='header'>
		<xsd:complexType>
			<xsd:sequence minOccurs='0' maxOccurs='unbounded'>
				<xsd:choice>
					<xsd:element ref='doc:para' />
					<xsd:element ref='doc:image' />
					<xsd:element ref='doc:phrase' />
				</xsd:choice>
			</xsd:sequence>
			<xsd:attribute name='border-width' type='xsd:string' use='optional' />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name='footer'>
		<xsd:complexType>
			<xsd:sequence minOccurs='0' maxOccurs='unbounded'>
				<xsd:choice>
					<xsd:element ref='doc:para' />
					<xsd:element ref='doc:image' />
					<xsd:element ref='doc:phrase' />
				</xsd:choice>
			</xsd:sequence>
			<xsd:attribute name='border-width' type='xsd:string' use='optional' />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name='header-ext'>
		<xsd:complexType>
			<xsd:sequence minOccurs='0' maxOccurs='unbounded'>
				<xsd:choice>
					<xsd:element ref='doc:para' />
					<xsd:element ref='doc:table' />
					<xsd:element ref='doc:image' />
					<xsd:element ref='doc:phrase' />
					<xsd:element ref='doc:barcode' />
				</xsd:choice>
			</xsd:sequence>
			<xsd:attribute name='border-width' type='xsd:string' use='optional' />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name='footer-ext'>
		<xsd:complexType>
			<xsd:sequence minOccurs='0' maxOccurs='unbounded'>
				<xsd:choice>
					<xsd:element ref='doc:para' />
					<xsd:element ref='doc:table' />
					<xsd:element ref='doc:image' />
					<xsd:element ref='doc:phrase' />
					<xsd:element ref='doc:barcode' />
				</xsd:choice>
			</xsd:sequence>
			<xsd:attribute name='border-width' type='xsd:string' use='optional' />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name='body'>
		<xsd:complexType>
			<xsd:choice minOccurs='0' maxOccurs='unbounded'>
				<xsd:choice>
					<xsd:element ref='doc:para' />
					<xsd:element ref='doc:table' />
					<xsd:element ref='doc:image' />
					<xsd:element ref='doc:phrase' />
					<xsd:element ref='doc:barcode' />
				</xsd:choice>
				<xsd:element ref='doc:page-break' />
			</xsd:choice>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name='image'>
		<xsd:complexType mixed='true'>
			<xsd:attribute name='url' type='xsd:string' use='optional' />
			<xsd:attribute name='scaling' type='xsd:int' use='optional' />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name='barcode'>
		<xsd:complexType mixed='true'>
			<xsd:attribute name='size' type='xsd:int' use='optional' />
			<xsd:attribute name='type' type='xsd:string' use='optional' />
			<xsd:attribute name='text' type='xsd:string' use='optional' />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name='para'>
		<xsd:complexType mixed='true'>
			<xsd:attribute name='id' type='xsd:string' use='optional' />
			<xsd:attribute name='style' type='doc:styleType' use='optional' />
			<xsd:attribute name='align' type='doc:alignType' use='optional' />
			<xsd:attribute name='font-name' type='xsd:string' use='optional' />
			<xsd:attribute name='leading' type='xsd:decimal' use='optional' />
			<xsd:attribute name='back-color' type='doc:colorType' use='optional' />
			<xsd:attribute name='fore-color' type='doc:colorType' use='optional' />
			<xsd:attribute name='type' type='xsd:string' use='optional' />
			<xsd:attribute name='size' type="xsd:int" use='optional' />
			<xsd:attribute name='space-before' type='xsd:decimal' use='optional' />
			<xsd:attribute name='space-after' type="xsd:decimal" use='optional' />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name='phrase'>
		<xsd:complexType mixed='true'>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name='table'>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref='doc:row' minOccurs='0' maxOccurs='unbounded' />
			</xsd:sequence>
			<xsd:attribute name='id' type='xsd:string' use='optional' />
			<xsd:attribute name='columns' type='xsd:string' use='optional' />
			<xsd:attribute name='width' type='xsd:int' use='optional' />
			<xsd:attribute name='back-color' type='doc:colorType' use='optional' />
			<xsd:attribute name='fore-color' type='doc:colorType' use='optional' />
			<xsd:attribute name='spacing' type='xsd:int' use='optional' />
			<xsd:attribute name='padding' type='xsd:int' use='optional' />
			<xsd:attribute name='colwidths' type='xsd:string' use='optional' />
			<xsd:attribute name='space-before' type='xsd:decimal' use='optional' />
			<xsd:attribute name='space-after' type='xsd:decimal' use='optional' />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name='row'>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref='doc:cell' minOccurs='0' maxOccurs='unbounded' />
			</xsd:sequence>
			<xsd:attribute name='id' type='xsd:string' use='optional' />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name='cell'>
		<xsd:complexType>
			<xsd:sequence minOccurs='0' maxOccurs='unbounded'>
				<xsd:choice>
					<xsd:element ref='doc:para' />
					<xsd:element ref='doc:table' />
					<xsd:element ref='doc:image' />
					<xsd:element ref='doc:phrase' />
					<xsd:element ref='doc:barcode' />
				</xsd:choice>
			</xsd:sequence>
			<xsd:attribute name='id' type='xsd:string' use='optional' />
			<xsd:attribute name='colspan' type='xsd:string' use='optional' />
			<xsd:attribute name='rowspan' type='xsd:string' use='optional' />
			<xsd:attribute name='align' type='doc:alignType' use='optional' />
			<xsd:attribute name='valign' type='doc:valignType' use='optional' />
			<xsd:attribute name='header' type="xsd:boolean" use='optional' />
			<xsd:attribute name='border-color' type='doc:colorType' use='optional' />
			<xsd:attribute name='border-color-top' type='doc:colorType' use='optional' />
			<xsd:attribute name='border-color-bottom' type='doc:colorType' use='optional' />
			<xsd:attribute name='border-color-left' type='doc:colorType' use='optional' />
			<xsd:attribute name='border-color-right' type='doc:colorType' use='optional' />
			<xsd:attribute name='border-width' type='xsd:int' use='optional' />
			<xsd:attribute name='border-width-top' type='xsd:int' use='optional' />
			<xsd:attribute name='border-width-bottom' type='xsd:int' use='optional' />
			<xsd:attribute name='border-width-left' type='xsd:int' use='optional' />
			<xsd:attribute name='border-width-right' type='xsd:int' use='optional' />						
		</xsd:complexType>
	</xsd:element>

	<xsd:element name='page-break'>
		<xsd:complexType />
	</xsd:element>

	<xsd:simpleType name="styleType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="bold"></xsd:enumeration>
			<xsd:enumeration value="underline"></xsd:enumeration>
			<xsd:enumeration value="italic"></xsd:enumeration>
			<xsd:enumeration value="bolditalic"></xsd:enumeration>
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:simpleType name="alignType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="center"></xsd:enumeration>
			<xsd:enumeration value="right"></xsd:enumeration>
			<xsd:enumeration value="left"></xsd:enumeration>
			<xsd:enumeration value="justify"></xsd:enumeration>
			<xsd:enumeration value="justifyall"></xsd:enumeration>
		</xsd:restriction>
	</xsd:simpleType>	
	
	<xsd:simpleType name="valignType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="middle"></xsd:enumeration>
			<xsd:enumeration value="top"></xsd:enumeration>
			<xsd:enumeration value="bottom"></xsd:enumeration>
		</xsd:restriction>
	</xsd:simpleType>		
	
	<xsd:simpleType name="colorType">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="#([A-Fa-f0-9]{6})"></xsd:pattern>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:complexType name="metaType">
		<xsd:sequence>
			<xsd:element ref='doc:info' minOccurs='0' maxOccurs='unbounded' />
			<xsd:element ref='doc:header' minOccurs='0' maxOccurs='1' />
			<xsd:element ref='doc:footer' minOccurs='0' maxOccurs='1' />
			<xsd:element ref='doc:header-ext' minOccurs='0' maxOccurs='1' />
			<xsd:element ref='doc:footer-ext' minOccurs='0' maxOccurs='1' />
		</xsd:sequence>
	</xsd:complexType>	

</xsd:schema>

=== daneeldeveloper/fj-doc/fj-doc-sample/src/main/resources/free_marker/test_01.xml
<?xml version="1.0" encoding="utf-8"?>
<doc
	xmlns="http://javacoredoc.fugerit.org"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://javacoredoc.fugerit.org http://www.fugerit.org/data/java/doc/xsd/doc-1-0.xsd" > 

  <!-- 
  	Sample Apache FreeMarker template for Fugerit Doc.
  	Note : this example has no intention of being a guid to FreeMarker
  			(In case check FreeMarker documentation https://freemarker.apache.org/docs/index.html)
   -->

  <meta>
  
  	<!-- Margin for document : left;right;top;bottom -->
  	<info name="margins">10;10;10;30</info>  
  
	<info name="excel-table-id">excel-table=print</info>
	<info name="excel-width-multiplier">450</info>
	
	<!-- you need to escape free marker expression for currentPage --> 
	<footer-ext numbered="true" align="right">
		<para>${r"${currentPage}"}</para>
	</footer-ext>
	 
  </meta>
 
  <body>
  
  		<phrase>Test template page apache free marker</phrase>
  
  		<image url="cl://test/img_test_green.png" scaling="100"/>
  
  		<image url="cl://test/img_test_red.png" scaling="50"/>
  
  		<image url="png" base64="${testBase64Img}" scaling="25"/>	
  
    	<table columns="3" colwidths="30;30;40"  width="100" id="excel-table" padding="2">
    		<row>
    			<cell align="center" border-color="#ee0000" border-width="1"><para style="bold">Name</para></cell>
    			<cell align="center"><para style="bold">Surname</para></cell>
    			<cell align="center"><para style="bold">Title</para></cell>
    		</row>
			<#list userList as user>
				<#include "/include/test_01_row.xml">
			</#list>   		
    	</table>
  </body>
  
</doc>

=== daneeldeveloper/fj-doc/fj-doc-sample/src/main/resources/free_marker/basic.xml
<?xml version="1.0" encoding="utf-8"?>
<doc
	xmlns="http://javacoredoc.fugerit.org"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://javacoredoc.fugerit.org http://www.fugerit.org/data/java/doc/xsd/doc-1-0.xsd" > 

  <!-- 
  	Sample Apache FreeMarker template for Fugerit Doc.
  	Note : this example has no intention of being a guid to FreeMarker
  			(In case check FreeMarker documentation https://freemarker.apache.org/docs/index.html)
   -->

  <meta>
	<info name="excel-table-id">excel-table=print</info>
	<info name="excel-width-multiplier">450</info> 
  </meta>
 
  <body>
  
  		<phrase>Test template page apache free marker</phrase>
  
    	<table columns="3" colwidths="30;30;40"  width="100" id="excel-table" padding="2">
    		<row>
    			<cell align="center" border-color="#000000" border-width="1"><para style="bold">Name</para></cell>
    			<cell align="center"><para style="bold">Surname</para></cell>
    			<cell align="center"><para style="bold">Title</para></cell>
    		</row>
			<#list userList as user>
       		<row>
    			<cell><para><#if (user.name)??>${user.name}</#if></para></cell>
    			<cell><para><#if (user.surname)??>${user.surname}</#if></para></cell>
    			<cell><para><#if (user.title)??>${user.title}</#if></para></cell>
    		</row>
			</#list>   		
    	</table>
  </body>
  
</doc>

=== daneeldeveloper/fj-doc/fj-doc-sample/src/test/resources/sample_docs/basic.xml
<?xml version="1.0" encoding="utf-8"?>
<doc
	xmlns="http://javacoredoc.fugerit.org"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://javacoredoc.fugerit.org http://www.fugerit.org/data/java/doc/xsd/doc-1-0.xsd" > 

  <meta>
	<info name="excel-table-id">excel-table=print</info>
	<info name="excel-width-multiplier">450</info> 
  </meta>

  <body>
    	<table columns="3" colwidths="30;30;40"  width="100" id="excel-table" padding="2">
    		<row>
    			<cell align="center"><para style="bold">Name</para></cell>
    			<cell align="center"><para style="bold">Surname</para></cell>
    			<cell align="center"><para style="bold">Title</para></cell>
    		</row>
       		<row>
    			<cell><para>Luthien</para></cell>
    			<cell><para>Tinuviel</para></cell>
    			<cell><para>Queen</para></cell>
    		</row>
       		<row>
    			<cell><para>Thorin</para></cell>
    			<cell><para>Oakshield</para></cell>
    			<cell><para>King</para></cell>
    		</row>    		
    	</table>
  </body>
  
</doc>
